version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kertmuftah-app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - kertmuftah-network

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kertmuftah
      MYSQL_ROOT_PASSWORD: muftah123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kertmuftah-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - kertmuftah-network

volumes:
  dbdata:
networks:
  kertmuftah-network:
    driver: bridge